name: gitleaks
on: 
  pull_request: 
  push: 
  workflow_dispatch: 
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_CONFIG: .gitleaks.toml
          GITLEAKS_FLAGS: --verbose --no-git

      - name: Display Gitleaks version
        run: gitleaks version

      - name: List scanned files
        run: find . -type f | grep -v '.git'