name: Pytest Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Clone and install vl-research
      env:
        VL_RESEARCH_PAT: ${{ secrets.VL_RESEARCH_PAT }}
      run: |
        git clone https://${VL_RESEARCH_PAT}@github.com/visual-layer/vl-research.git
        cd vl-research
        pip install -e .
        cd ..
    
    - name: Install current package
      run: pip install .
    
    - name: Run tests
      run: pytest -v --ignore=vl-research